# Generated by Django 5.0.4 on 2024-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_articles_options_remove_articles_anons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='news_img',
            field=models.ImageField(default='', upload_to='uploads/% Y/% m/% d/', verbose_name='Изображение'),
        ),
    ]
