# Generated by Django 5.0.4 on 2024-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_articles_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseName', models.CharField(max_length=64, verbose_name='Название релиза')),
                ('artistName', models.CharField(max_length=64, verbose_name='Никнейм артиста')),
                ('releaseGenre', models.CharField(max_length=64, verbose_name='Жанр')),
                ('releaseType', models.CharField(max_length=32, verbose_name='Тип релиза')),
                ('artistLink', models.CharField(max_length=512, verbose_name='Ссылка на профиль артиста')),
                ('releaseUPC', models.CharField(max_length=32, verbose_name='UPC')),
                ('releaseDate', models.DateTimeField(verbose_name='Дата релиза')),
                ('artistRealName', models.CharField(max_length=256, verbose_name='ФИО Ариста')),
                ('eclipticContent', models.CharField(max_length=16, verbose_name='Нецензурная лексика')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
            },
        ),
    ]
