# Generated by Django 5.0.4 on 2024-04-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_release_releaescover_alter_release_eclipticcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='eclipticContent',
            field=models.CharField(max_length=16, verbose_name='Нецензурная лексика'),
        ),
    ]
